package es.ull.simulation.inforeceiver;

import es.ull.simulation.info.IPieceOfInformation;

/**
 * A common interface for all the classes that handle information generated by components of the simulation experiments.
 */
public interface IHandlesInformation {
	/**
	 * Registers a listener to receive information of a certain type.
	 * @param listener The listener that wants to receive the information.
	 */
	public void registerListener(BasicListener listener);

	/**
	 * Notifies the listeners that a piece of information has been generated.
	 * @param info The piece of information that has been generated.
	 */
    public void notifyInfo(IPieceOfInformation info);
}
